version: '3.3'
services:
  elastic:
    image: elasticsearch:8.6.2
    container_name: elastic_tests
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    restart: always
    ports:
      - "9200:9200"
    expose:
      - 9200
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 50

  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

  api:
    container_name: movies_api_tests
    build: ./movies_api
    env_file: ./.env
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - 8000
    ports:
      - '8000:8000'

  tests:
    container_name: functional_tests
    image: python:3.8
    env_file:
      - ./.env
    volumes:
      - ./movies_api/tests/:/usr/src/tests
    entrypoint: >
      sh -c "pip install --upgrade pip
      && pip install -r /usr/src/tests/functional/requirements.txt
      && python /usr/src/tests/functional/utils/wait_for_es.py
      && python /usr/src/tests/functional/utils/wait_for_redis.py
      && pytest /usr/src/tests/functional/src"
    depends_on:
      api:
        condition:
          service_started

volumes:
  redis_data: