"""initial

Revision ID: aa72f6b6680f
Revises: 8b7fecba0297
Create Date: 2024-04-24 17:18:01.298512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa72f6b6680f'
down_revision: Union[str, None] = '8b7fecba0297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('service_payment_id', sa.UUID(), nullable=False))
    op.drop_constraint('user_subscriptions_last_payment_id_fkey', 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscriptions', 'payments', ['service_payment_id'], ['id'])
    op.drop_column('user_subscriptions', 'last_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('last_payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key('user_subscriptions_last_payment_id_fkey', 'user_subscriptions', 'payments', ['last_payment_id'], ['id'])
    op.drop_column('user_subscriptions', 'service_payment_id')
    # ### end Alembic commands ###
