"""initial

Revision ID: caad1a8ffdc4
Revises: 033e6de8d4e5
Create Date: 2024-04-24 14:44:20.176915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caad1a8ffdc4'
down_revision: Union[str, None] = '033e6de8d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('yookassa_payment_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'payments', ['id'])
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    op.create_unique_constraint(None, 'user_subscriptions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscriptions', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'yookassa_payment_id')
    # ### end Alembic commands ###
