"""initial

Revision ID: f292046e6350
Revises: 15ea589b0791
Create Date: 2024-04-24 15:04:55.960677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f292046e6350'
down_revision: Union[str, None] = '15ea589b0791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_id', sa.UUID(), nullable=False))
    op.drop_column('payments', 'yookassa_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('yookassa_payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'payment_id')
    # ### end Alembic commands ###
